spring:
  profiles.active: default
---
spring:
  profiles: default
  basic.enabled: false
  thymeleaf.cache: false
  jpa.hibernate.ddl-auto: create-drop
spring.datasource:
  driverClassName: org.hsqldb.jdbcDriver
  url: jdbc:hsqldb:mem:scratchdb
  username: sa
  password:
# management:
#   security:
#     enabled: true
#     role: ADMIN
---
spring:
  profiles: qa
spring.datasource:
  url: jdbc:mysql://qa.myapp.com:3306/myappdb?autoReconnect=true
  username: qauser
  password: qapassword